---
title: "List Datasets"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Setup 

```{r setup}
## assumes you have client JSON saved to environment argument GAR_CLIENT_JSON
app_project <- googleAuthR::gar_set_client(
  scopes = c("https://www.googleapis.com/auth/cloud-platform"))

library(bigQueryR)
library(googleCloudAutoMLTablesR)

googleAuthR::gar_auth("gcp.oauth")
```

Test authentication and check in correct project: 

```{r}
bqr_list_projects()
```

# Loading data into AutoML Tables 

## Get list of locations 
```{r}
amlt_locations <- amltr_list_locations(projectId = "projects/snappy-way-531")

amlt_location <- amlt_locations$locations$name[1]
```

## Get list of datasets 
```{r}
amlt_datasets <- projects.locations.datasets.list(amlt_location)
# amltr_list_datasets(projectId = "")

amlt_datasets$datasets[, c("displayName", "createTime", "etag", "name")]
```
