---
title: "Quick Start"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Setup 

```{r setup}
# assumes you have client JSON saved to environment argument GAR_CLIENT_JSON
app_project <- googleAuthR::gar_set_client(
  scopes = c("https://www.googleapis.com/auth/cloud-platform"))

library(googleAuthR)
library(googleCloudAutoMLTablesR)
options(googleAuthR.verbose = 0)

gar_auth("gcat.oauth")
```

Test authentication and check in correct project: 

```{r}
# assumes you have projectId string set to environment 
# argument GCAT_PROJECT_ID
projectId <- Sys.getenv("GCAT_PROJECT_ID")

## Get list of locations 
gcat_locations <- gcat_list_locations(projectId = projectId)
gcat_locations$locations
```

## Set location 

```{r}
## manually set location path TODO - @justinjm - update function to handle 
## location setting 
gcat_location <- "us-central1"
gcat_location_path(projectId, gcat_location)
```

## Get list of datasets 

```{r}
gcat_datasets <- gcat_list_datasets(projectId = projectId,
                                    location = gcat_location)

gcat_datasets$datasets[, c("displayName", "createTime", "etag", "name")]
```

# Loading data into AutoML Tables 

## Create dataset 
```{r}
gcat_create_dataset(projectId = projectId,
                    location = gcat_location,
                    displayName = "test_02")
```

### view debugging info 
```{r}
readRDS("request_debug.rds")
```

### Error 

```r
-> POST /v1beta1/projects/xxxx/locations/us-central1/datasets HTTP/1.1
-> Host: automl.googleapis.com
-> User-Agent: googleAuthR/0.7.0 (gzip)
-> Accept: application/json, text/xml, application/xml, */*
-> Content-Type: application/json
-> Accept-Encoding: gzip
-> Authorization: Bearer xxxx
-> Content-Length: 55
-> 
>> {"displayName":"test_02","tablesDatasetMetadata":"{ }"}

<- HTTP/1.1 400 Bad Request
<- Vary: Origin
<- Vary: X-Origin
<- Vary: Referer
<- Content-Type: application/json; charset=UTF-8
<- Content-Encoding: gzip
<- Date: Thu, 11 Jul 2019 19:38:26 GMT
<- Server: ESF
<- Cache-Control: private
<- X-XSS-Protection: 0
<- X-Frame-Options: SAMEORIGIN
<- X-Content-Type-Options: nosniff
<- Alt-Svc: quic=":443"; ma=2592000; v="46,43,39"
<- Transfer-Encoding: chunked
<- 
2019-07-11 15:38:26> Request Status Code: 400
2019-07-11 15:38:26> API returned error: Invalid value at 'dataset.tables_dataset_metadata' (type.googleapis.com/google.cloud.automl.v1beta1.TablesDatasetMetadata), "{ }"
2019-07-11 15:38:26> No retry attempted: Invalid value at 'dataset.tables_dataset_metadata' (type.googleapis.com/google.cloud.automl.v1beta1.TablesDatasetMetadata), "{ }"
Scopes: https://www.googleapis.com/auth/cloud-platform
App key: xxxx.apps.googleusercontent.com
Method: filepath
Error: API returned: Invalid value at 'dataset.tables_dataset_metadata' (type.googleapis.com/google.cloud.automl.v1beta1.TablesDatasetMetadata), "{ }"
```

### Debug 

```r
$url
[1] "https://automl.googleapis.com/v1beta1/projects/xxxx/locations/us-central1/datasets"

$request_type
[1] "POST"

$body_json
{"displayName":"test_02","tablesDatasetMetadata":"{ }"} 
```
