#' Cloud AutoML API
#' Train high-quality custom machine learning models with minimum effort and machine learning expertise.
#' 
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2019-04-28 16:49:49
#' api_json: api_json
#' 
#' @details 
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' @docType package 
#' @name automl_googleAuthR
#' 
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x)) 
        rmNullObs(x) else x)
}

#' Gets the access control policy for a resource.Returns an empty policy if the resource exists and does not have a policyset.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param resource REQUIRED: The resource for which the policy is being requested
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.getIamPolicy <- function(resource) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+resource}:getIamPolicy", 
        resource)
    # automl.projects.locations.getIamPolicy
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Lists information about the supported locations for this service.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource that owns the locations collection, if applicable
#' @param pageToken The standard list page token
#' @param pageSize The standard list page size
#' @param filter The standard list filter
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.list <- function(name, pageToken = NULL, pageSize = NULL, filter = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}/locations", name)
    # automl.projects.locations.list
    pars = list(pageToken = pageToken, pageSize = pageSize, filter = filter)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Gets information about a location.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Resource name for the location
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.get <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}", name)
    # automl.projects.locations.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Sets the access control policy on the specified resource. Replaces anyexisting policy.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param SetIamPolicyRequest The \link{SetIamPolicyRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy is being specified
#' @importFrom googleAuthR gar_api_generator
#' @family SetIamPolicyRequest functions
#' @export
projects.locations.setIamPolicy <- function(SetIamPolicyRequest, resource) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+resource}:setIamPolicy", 
        resource)
    # automl.projects.locations.setIamPolicy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(SetIamPolicyRequest, "gar_SetIamPolicyRequest"))
    
    f(the_body = SetIamPolicyRequest)
    
}

#' Returns permissions that a caller has on the specified resource.If the resource does not exist, this will return an empty set ofpermissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-awareUIs and command-line tools, not for authorization checking. This operationmay 'fail open' without warning.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param TestIamPermissionsRequest The \link{TestIamPermissionsRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy detail is being requested
#' @importFrom googleAuthR gar_api_generator
#' @family TestIamPermissionsRequest functions
#' @export
projects.locations.testIamPermissions <- function(TestIamPermissionsRequest, resource) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+resource}:testIamPermissions", 
        resource)
    # automl.projects.locations.testIamPermissions
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(TestIamPermissionsRequest, "gar_TestIamPermissionsRequest"))
    
    f(the_body = TestIamPermissionsRequest)
    
}

#' Imports data into a dataset.For Tables this method can only be called on an empty Dataset.For Tables:*   Aschema_inference_version    parameter must be explicitly set.Returns an empty response in theresponse field when it completes.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param ImportDataRequest The \link{ImportDataRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family ImportDataRequest functions
#' @export
projects.locations.datasets.importData <- function(ImportDataRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}:importData", name)
    # automl.projects.locations.datasets.importData
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(ImportDataRequest, "gar_ImportDataRequest"))
    
    f(the_body = ImportDataRequest)
    
}

#' Deletes a dataset and all of its contents.Returns empty response in theresponse field when it completes,and `delete_details` in themetadata field.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the dataset to delete
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.datasets.delete <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}", name)
    # automl.projects.locations.datasets.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()
    
}

#' Lists datasets in a project.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent The resource name of the project from which to list datasets
#' @param filter An expression for filtering the results of the request
#' @param pageToken A token identifying a page of results for the server to return
#' @param pageSize Requested page size
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.datasets.list <- function(parent, filter = NULL, pageToken = NULL, 
    pageSize = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+parent}/datasets", parent)
    # automl.projects.locations.datasets.list
    pars = list(filter = filter, pageToken = pageToken, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Creates a dataset.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Dataset The \link{Dataset} object to pass to this method
#' @param parent The resource name of the project to create the dataset for
#' @importFrom googleAuthR gar_api_generator
#' @family Dataset functions
#' @export
projects.locations.datasets.create <- function(Dataset, parent) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+parent}/datasets", parent)
    # automl.projects.locations.datasets.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(Dataset, "gar_Dataset"))
    
    f(the_body = Dataset)
    
}

#' Sets the access control policy on the specified resource. Replaces anyexisting policy.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param SetIamPolicyRequest The \link{SetIamPolicyRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy is being specified
#' @importFrom googleAuthR gar_api_generator
#' @family SetIamPolicyRequest functions
#' @export
projects.locations.datasets.setIamPolicy <- function(SetIamPolicyRequest, resource) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+resource}:setIamPolicy", 
        resource)
    # automl.projects.locations.datasets.setIamPolicy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(SetIamPolicyRequest, "gar_SetIamPolicyRequest"))
    
    f(the_body = SetIamPolicyRequest)
    
}

#' Gets the access control policy for a resource.Returns an empty policy if the resource exists and does not have a policyset.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param resource REQUIRED: The resource for which the policy is being requested
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.datasets.getIamPolicy <- function(resource) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+resource}:getIamPolicy", 
        resource)
    # automl.projects.locations.datasets.getIamPolicy
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Updates a dataset.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Dataset The \link{Dataset} object to pass to this method
#' @param name Output only
#' @param updateMask The update mask applies to the resource
#' @importFrom googleAuthR gar_api_generator
#' @family Dataset functions
#' @export
projects.locations.datasets.patch <- function(Dataset, name, updateMask = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}", name)
    # automl.projects.locations.datasets.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    stopifnot(inherits(Dataset, "gar_Dataset"))
    
    f(the_body = Dataset)
    
}

#' Gets a dataset.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the dataset to retrieve
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.datasets.get <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}", name)
    # automl.projects.locations.datasets.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Exports dataset's data to the provided output location.Returns an empty response in theresponse field when it completes.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param ExportDataRequest The \link{ExportDataRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family ExportDataRequest functions
#' @export
projects.locations.datasets.exportData <- function(ExportDataRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}:exportData", name)
    # automl.projects.locations.datasets.exportData
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(ExportDataRequest, "gar_ExportDataRequest"))
    
    f(the_body = ExportDataRequest)
    
}

#' Gets an annotation spec.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the annotation spec to retrieve
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.datasets.annotationSpecs.get <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}", name)
    # automl.projects.locations.datasets.annotationSpecs.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Gets a table spec.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the table spec to retrieve
#' @param fieldMask Mask specifying which fields to read
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.datasets.tableSpecs.get <- function(name, fieldMask = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}", name)
    # automl.projects.locations.datasets.tableSpecs.get
    pars = list(fieldMask = fieldMask)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Lists table specs in a dataset.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent The resource name of the dataset to list table specs from
#' @param fieldMask Mask specifying which fields to read
#' @param pageToken A token identifying a page of results for the server to return
#' @param pageSize Requested page size
#' @param filter Filter expression, see go/filtering
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.datasets.tableSpecs.list <- function(parent, fieldMask = NULL, 
    pageToken = NULL, pageSize = NULL, filter = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+parent}/tableSpecs", 
        parent)
    # automl.projects.locations.datasets.tableSpecs.list
    pars = list(fieldMask = fieldMask, pageToken = pageToken, pageSize = pageSize, 
        filter = filter)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Updates a table spec.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param TableSpec The \link{TableSpec} object to pass to this method
#' @param name Output only
#' @param updateMask The update mask applies to the resource
#' @importFrom googleAuthR gar_api_generator
#' @family TableSpec functions
#' @export
projects.locations.datasets.tableSpecs.patch <- function(TableSpec, name, updateMask = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}", name)
    # automl.projects.locations.datasets.tableSpecs.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    stopifnot(inherits(TableSpec, "gar_TableSpec"))
    
    f(the_body = TableSpec)
    
}

#' Gets a column spec.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The resource name of the column spec to retrieve
#' @param fieldMask Mask specifying which fields to read
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.datasets.tableSpecs.columnSpecs.get <- function(name, fieldMask = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}", name)
    # automl.projects.locations.datasets.tableSpecs.columnSpecs.get
    pars = list(fieldMask = fieldMask)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Lists column specs in a table spec.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent The resource name of the table spec to list column specs from
#' @param filter Filter expression, see go/filtering
#' @param fieldMask Mask specifying which fields to read
#' @param pageToken A token identifying a page of results for the server to return
#' @param pageSize Requested page size
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.datasets.tableSpecs.columnSpecs.list <- function(parent, filter = NULL, 
    fieldMask = NULL, pageToken = NULL, pageSize = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+parent}/columnSpecs", 
        parent)
    # automl.projects.locations.datasets.tableSpecs.columnSpecs.list
    pars = list(filter = filter, fieldMask = fieldMask, pageToken = pageToken, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Updates a column spec.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param ColumnSpec The \link{ColumnSpec} object to pass to this method
#' @param name Output only
#' @param updateMask The update mask applies to the resource
#' @importFrom googleAuthR gar_api_generator
#' @family ColumnSpec functions
#' @export
projects.locations.datasets.tableSpecs.columnSpecs.patch <- function(ColumnSpec, 
    name, updateMask = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}", name)
    # automl.projects.locations.datasets.tableSpecs.columnSpecs.patch
    pars = list(updateMask = updateMask)
    f <- googleAuthR::gar_api_generator(url, "PATCH", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    stopifnot(inherits(ColumnSpec, "gar_ColumnSpec"))
    
    f(the_body = ColumnSpec)
    
}

#' Starts asynchronous cancellation on a long-running operation.  The servermakes a best effort to cancel the operation, but success is notguaranteed.  If the server doesn't support this method, it returns`google.rpc.Code.UNIMPLEMENTED`.  Clients can useOperations.GetOperation orother methods to check whether the cancellation succeeded or whether theoperation completed despite cancellation. On successful cancellation,the operation is not deleted; instead, it becomes an operation withan Operation.error value with a google.rpc.Status.code of 1,corresponding to `Code.CANCELLED`.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param CancelOperationRequest The \link{CancelOperationRequest} object to pass to this method
#' @param name The name of the operation resource to be cancelled
#' @importFrom googleAuthR gar_api_generator
#' @family CancelOperationRequest functions
#' @export
projects.locations.operations.cancel <- function(CancelOperationRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}:cancel", name)
    # automl.projects.locations.operations.cancel
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(CancelOperationRequest, "gar_CancelOperationRequest"))
    
    f(the_body = CancelOperationRequest)
    
}

#' Deletes a long-running operation. This method indicates that the client isno longer interested in the operation result. It does not cancel theoperation. If the server doesn't support this method, it returns`google.rpc.Code.UNIMPLEMENTED`.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The name of the operation resource to be deleted
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.operations.delete <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}", name)
    # automl.projects.locations.operations.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()
    
}

#' Lists operations that match the specified filter in the request. If theserver doesn't support this method, it returns `UNIMPLEMENTED`.NOTE: the `name` binding allows API services to override the bindingto use different resource name schemes, such as `users/*/operations`. Tooverride the binding, API services can add a binding such as`'/v1/{name=users/*}/operations'` to their service configuration.For backwards compatibility, the default name includes the operationscollection id, however overriding users must ensure the name bindingis the parent resource, without the operations collection id.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The name of the operation's parent resource
#' @param filter An expression for filtering the results of the request
#' @param pageToken The standard list page token
#' @param pageSize The standard list page size
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.operations.list <- function(name, filter = NULL, pageToken = NULL, 
    pageSize = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}/operations", name)
    # automl.projects.locations.operations.list
    pars = list(filter = filter, pageToken = pageToken, pageSize = pageSize)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Gets the latest state of a long-running operation.  Clients can use thismethod to poll the operation result at intervals as recommended by the APIservice.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name The name of the operation resource
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.operations.get <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}", name)
    # automl.projects.locations.operations.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Waits for the specified long-running operation until it is done or reachesat most a specified timeout, returning the latest state.  If the operationis already done, the latest state is immediately returned.  If the timeoutspecified is greater than the default HTTP/RPC timeout, the HTTP/RPCtimeout is used.  If the server does not support this method, it returns`google.rpc.Code.UNIMPLEMENTED`.Note that this method is on a best-effort basis.  It may return the lateststate before the specified timeout (including immediately), meaning even animmediate response is no guarantee that the operation is done.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param WaitOperationRequest The \link{WaitOperationRequest} object to pass to this method
#' @param name The name of the operation resource to wait on
#' @importFrom googleAuthR gar_api_generator
#' @family WaitOperationRequest functions
#' @export
projects.locations.operations.wait <- function(WaitOperationRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}:wait", name)
    # automl.projects.locations.operations.wait
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(WaitOperationRequest, "gar_WaitOperationRequest"))
    
    f(the_body = WaitOperationRequest)
    
}

#' Perform a batch prediction. Unlike the online Predict, batchprediction result won't be immediately available in the response. Instead,a long running operation object is returned. User can poll the operationresult via GetOperationmethod. Once the operation is done, BatchPredictResult is returned inthe response field.Available for following ML problems: * Video Classification * Text Extraction* Tables
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param BatchPredictRequest The \link{BatchPredictRequest} object to pass to this method
#' @param name Name of the model requested to serve the batch prediction
#' @importFrom googleAuthR gar_api_generator
#' @family BatchPredictRequest functions
#' @export
projects.locations.models.batchPredict <- function(BatchPredictRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}:batchPredict", 
        name)
    # automl.projects.locations.models.batchPredict
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(BatchPredictRequest, "gar_BatchPredictRequest"))
    
    f(the_body = BatchPredictRequest)
    
}

#' Lists models.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent Resource name of the project, from which to list the models
#' @param pageToken A token identifying a page of results for the server to return
#' @param pageSize Requested page size
#' @param filter An expression for filtering the results of the request
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.models.list <- function(parent, pageToken = NULL, pageSize = NULL, 
    filter = NULL) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+parent}/models", parent)
    # automl.projects.locations.models.list
    pars = list(pageToken = pageToken, pageSize = pageSize, filter = filter)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    f()
    
}

#' Creates a model.Returns a Model in the responsefield when it completes.When you create a model, several model evaluations are created for it:a global evaluation, and one evaluation for each annotation spec.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param Model The \link{Model} object to pass to this method
#' @param parent Resource name of the parent project where the model is being created
#' @importFrom googleAuthR gar_api_generator
#' @family Model functions
#' @export
projects.locations.models.create <- function(Model, parent) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+parent}/models", parent)
    # automl.projects.locations.models.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(Model, "gar_Model"))
    
    f(the_body = Model)
    
}

#' Deploys a model. If a model is already deployed, deploying it with thesame parameters has no effect. Deploying with different parametrs(as e.g. changingnode_number) will reset the deployment state without pausing the model's availability.Only applicable for Text Classification, Image Object Detection and Tables;all other domains manage deployment automatically.Returns an empty response in theresponse field when it completes.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param DeployModelRequest The \link{DeployModelRequest} object to pass to this method
#' @param name Resource name of the model to deploy
#' @importFrom googleAuthR gar_api_generator
#' @family DeployModelRequest functions
#' @export
projects.locations.models.deploy <- function(DeployModelRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}:deploy", name)
    # automl.projects.locations.models.deploy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(DeployModelRequest, "gar_DeployModelRequest"))
    
    f(the_body = DeployModelRequest)
    
}

#' Perform an online prediction. The prediction result will be directlyreturned in the response.Available for following ML problems, and their expected request payloads:* Image Classification - Image in .JPEG, .GIF or .PNG format, image_bytes                         up to 30MB.* Image Object Detection - Image in .JPEG, .GIF or .PNG format, image_bytes                           up to 30MB. * Text Classification - TextSnippet, content up to 60,000 characters,                        UTF-8 encoded.* Text Extraction - TextSnippet, content up to 30,000 characters,                    UTF-8 NFC encoded. * Translation - TextSnippet, content up to 25,000 characters, UTF-8                encoded.* Tables - Row, with column values matching the columns of the model,           up to 5MB. Not available for FORECASTINGprediction_type.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param PredictRequest The \link{PredictRequest} object to pass to this method
#' @param name Name of the model requested to serve the prediction
#' @importFrom googleAuthR gar_api_generator
#' @family PredictRequest functions
#' @export
projects.locations.models.predict <- function(PredictRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}:predict", name)
    # automl.projects.locations.models.predict
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(PredictRequest, "gar_PredictRequest"))
    
    f(the_body = PredictRequest)
    
}

#' Gets a model.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Resource name of the model
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.models.get <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}", name)
    # automl.projects.locations.models.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Exports examples on which the model was evaluated (i.e. which were in theTEST set of the dataset the model was created from), together with theirground truth annotations and the annotations created (predicted) by themodel.The examples, ground truth and predictions are exported in the statethey were at the moment the model was evaluated.This export is available only for 30 days since the model evaluation iscreated.Currently only available for Tables.Returns an empty response in theresponse field when it completes.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param ExportEvaluatedExamplesRequest The \link{ExportEvaluatedExamplesRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family ExportEvaluatedExamplesRequest functions
#' @export
projects.locations.models.exportEvaluatedExamples <- function(ExportEvaluatedExamplesRequest, 
    name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}:exportEvaluatedExamples", 
        name)
    # automl.projects.locations.models.exportEvaluatedExamples
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(ExportEvaluatedExamplesRequest, "gar_ExportEvaluatedExamplesRequest"))
    
    f(the_body = ExportEvaluatedExamplesRequest)
    
}

#' Deletes a model.Returns `google.protobuf.Empty` in theresponse field when it completes,and `delete_details` in themetadata field.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Resource name of the model being deleted
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.models.delete <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}", name)
    # automl.projects.locations.models.delete
    f <- googleAuthR::gar_api_generator(url, "DELETE", data_parse_function = function(x) x)
    f()
    
}

#' Sets the access control policy on the specified resource. Replaces anyexisting policy.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param SetIamPolicyRequest The \link{SetIamPolicyRequest} object to pass to this method
#' @param resource REQUIRED: The resource for which the policy is being specified
#' @importFrom googleAuthR gar_api_generator
#' @family SetIamPolicyRequest functions
#' @export
projects.locations.models.setIamPolicy <- function(SetIamPolicyRequest, resource) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+resource}:setIamPolicy", 
        resource)
    # automl.projects.locations.models.setIamPolicy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(SetIamPolicyRequest, "gar_SetIamPolicyRequest"))
    
    f(the_body = SetIamPolicyRequest)
    
}

#' Undeploys a model. If the model is not deployed this method has no effect.Only applicable for Text Classification, Image Object Detection and Tables;all other domains manage deployment automatically.Returns an empty response in theresponse field when it completes.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param UndeployModelRequest The \link{UndeployModelRequest} object to pass to this method
#' @param name Resource name of the model to undeploy
#' @importFrom googleAuthR gar_api_generator
#' @family UndeployModelRequest functions
#' @export
projects.locations.models.undeploy <- function(UndeployModelRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}:undeploy", name)
    # automl.projects.locations.models.undeploy
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(UndeployModelRequest, "gar_UndeployModelRequest"))
    
    f(the_body = UndeployModelRequest)
    
}

#' Exports a trained, 'export-able', model to a user specified Google CloudStorage location. A model is considered export-able if and only if it hasan export format defined for it inModelExportOutputConfig.Returns an empty response in theresponse field when it completes.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param ExportModelRequest The \link{ExportModelRequest} object to pass to this method
#' @param name Required
#' @importFrom googleAuthR gar_api_generator
#' @family ExportModelRequest functions
#' @export
projects.locations.models.export <- function(ExportModelRequest, name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}:export", name)
    # automl.projects.locations.models.export
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(ExportModelRequest, "gar_ExportModelRequest"))
    
    f(the_body = ExportModelRequest)
    
}

#' Gets the access control policy for a resource.Returns an empty policy if the resource exists and does not have a policyset.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param resource REQUIRED: The resource for which the policy is being requested
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.models.getIamPolicy <- function(resource) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+resource}:getIamPolicy", 
        resource)
    # automl.projects.locations.models.getIamPolicy
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}

#' Gets a model evaluation.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param name Resource name for the model evaluation
#' @importFrom googleAuthR gar_api_generator
#' @export
projects.locations.models.modelEvaluations.get <- function(name) {
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+name}", name)
    # automl.projects.locations.models.modelEvaluations.get
    f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
    f()
    
}


#' Lists model evaluations.
#' 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#' 
#' @seealso \href{https://cloud.google.com/automl}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' }
#' 
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/cloud-platform)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details. 
#' 
#' @param parent Resource name of the model to list the model evaluations for

#' @param pageToken A token identifying a page of results for the server to return

#' @param pageSize Requested page size

#' @param filter An expression for filtering the results of the request
#' @importFrom googleAuthR gar_api_generator
#' @export


projects.locations.models.modelEvaluations.list <- function(parent, pageToken = NULL, 
    pageSize = NULL, filter = NULL) {
    
    
    url <- sprintf("https://automl.googleapis.com/v1beta1/{+parent}/modelEvaluations", 
        parent)
    # automl.projects.locations.models.modelEvaluations.list
    pars = list(pageToken = pageToken, pageSize = pageSize, filter = filter)
    
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars), 
        data_parse_function = function(x) x)
    
    f()
    
    
}



